---
- import_playbook: 00.preparing.yml
- import_playbook: 01.base_packages.yml
- import_playbook: 02.setting_shared_volume.yml
- import_playbook: 03.setting_ntp.yml
- import_playbook: 04.settings_elasticsearch.yml
