---
- name: Write kafka_exporter.service
  ansible.builtin.copy:
    dest: "/etc/systemd/system/kafka_exporter.service"
    mode: "0644"
    owner: "root"
    group: "root"
    content: |-
      [Unit]
      Description=kafka_exporter
      After=network.target
      
      [Service]
      User={{ ansible_user }}
      Restart=on-failure
      Type=simple
      ExecStart={{ prometheus_base_dir }}/bin/kafka_exporter --kafka.server={{ hostvars[inventory_hostname].ansible_host }}:9092
      
      [Install]
      WantedBy=multi-user.target

- name: Enable and start kafka_exporter service
  ansible.builtin.systemd:
    name: kafka_exporter
    daemon_reload: true
    enabled: true
    state: started
