---
- name: Ensure prome packages dire in nfs
  ansible.builtin.file:
    path: "{{ prome_pkg_dir }}"
    state: directory
    mode: "0755"
    owner: "{{ ansible_user | default('wbl') }}"
    group: "{{ ansible_user | default('wbl') }}"

- name: Ensure prome tmp dir exists
  ansible.builtin.file:
    path: "{{ prome_tmp_dir }}"
    state: directory
    mode: "0755"
    owner: "{{ ansible_user | default('wbl') }}"
    group: "{{ ansible_user | default('wbl') }}"

- name: Find downloaded prome packages in tmp dir
  ansible.builtin.find:
    paths: "{{ prome_tmp_dir }}"
    file_type: file
  register: prome_tmp_dir

- name: Copy prome packages from tmp dir to nfs dir
  ansible.builtin.copy:
    src: "{{ item.path }}"
    dest: "{{ prome_pkg_dir }}/{{ item.path | basename }}"
    remote_src: true
    mode: "0644"
    owner: "{{ ansible_user | default('wbl') }}"
    group: "{{ ansible_user | default('wbl') }}"
  loop: "{{ prome_tmp_dir.files }}"
  loop_control:
    label: "{{ item.path | basename }}"
  when: prome_tmp_dir.matched | int > 0

- name: Remove prome packages from tmp dir after copy
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: absent
  loop: "{{ prome_tmp_dir.files }}"
  loop_control:
    label: "{{ item.path | basename }}"
  when: prome_tmp_dir.matched | int > 0
