---
- name: Write zookeeper_exporter.service
  ansible.builtin.copy:
    dest: "/etc/systemd/system/zookeeper_exporter.service"
    mode: "0644"
    owner: "root"
    group: "root"
    content: |-
      [Unit]
      Description=zookeeper-exporter
      After=network.target
      
      [Service]
      User={{ ansible_user }}
      Restart=on-failure
      Type=simple
      ExecStart={{ prometheus_base_dir }}/bin/zookeeper-exporter -listen={{ zoo_mon_endpoint }} -zk-hosts='{{ zoo_zk_hosts }}'
      
      [Install]
      WantedBy=multi-user.target

- name: Enable and start zookeeper_exporter service
  ansible.builtin.systemd:
    name: zookeeper_exporter
    daemon_reload: true
    enabled: true
    state: started
